// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNominaMVC.Data;

#nullable disable

namespace SistemaNominaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNominaMVC.Models.Department", b =>
                {
                    b.Property<int>("dept_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dept_no"));

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("dept_no");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Dept_Emp", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<int>("dept_no")
                        .HasColumnType("int");

                    b.Property<string>("from_date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("to_date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no", "dept_no");

                    b.ToTable("Dept_Emps");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Dept_Manager", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<int>("dept_no")
                        .HasColumnType("int");

                    b.Property<string>("from_date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("to_date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no", "dept_no");

                    b.ToTable("Dept_Managers");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Employee", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_no"));

                    b.Property<string>("birth_date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("hire_date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Log_AuditoriaSalarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaActualiz")
                        .HasColumnType("datetime2");

                    b.Property<long>("salario")
                        .HasColumnType("bigint");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Log_AuditoriaSalarios");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Salary", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<string>("from_date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("salary")
                        .HasColumnType("bigint");

                    b.Property<string>("to_date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no", "from_date");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.Title", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("from_date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("to_date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no", "title", "from_date");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("SistemaNominaMVC.Models.User", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_no"));

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("emp_no");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
